### ISSUE TITLE
Multiple font resizes upon page refresh on login page

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#646] opened 2023-08-11 07:52 UTC
### Platform

iOS

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

Yes I am

### Issue Details

1. Visit https://auth.adguard.com/login.html

### Expected Behavior

Expected behaviour is to not see fonts go through a resizing process every time the page is loaded

### Actual Behavior

Fonts seem to resize multiple times before settling when the page is reloaded.

### Screenshots

<details><summary>Screenshot 1:</summary>

https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/c62a8b94-d9d3-426a-beca-3f73b8a9fbd2

</details>

### Additional Information

Issue also occurs on the password, and 2FA page.

**Comment by ameshkov** [comment] 2023-08-13 20:06
Moved to internal task: ADG-7345

Closing it here since the issue is not specific to AG DNS but for the auth website in general.

**Closed by ameshkov** 2023-08-13 20:06 UTC
Labels: bug
