### ISSUE TITLE
AdGuard DNS scheduling feature

### ISSUE THREAD

**Issue by PavelParkhomenko** [AdguardTeam/AdGuardDNS#817] opened 2024-08-16 14:24 UTC
### Issue Details

Currently, internet connections can only be blocked by manually enabling a user rule, which can be inconvenient if this needs to be done daily.

### Proposed solution

Introduce the ability to set rules or schedules that automatically allow or block internet connections based on specified timeframes. For example, users could schedule internet access to be allowed only during work hours, such as 08:00-16:00

**Comment by emeritaacuity0u** [comment] 2024-08-16 20:26
Possible duplicate of #574.

**Comment by Chinaski1** [comment] 2024-08-26 09:56
Closed as duplicate

**Closed by Chinaski1** 2024-08-26 09:56 UTC
Labels: feature request

**Comment by ihurin** [comment] 2025-12-22 07:58
As a possible improvement of this feature, other customers ask to make user rules on schedule as well. So that access to specific websites is restricted on time. Or maybe this can be (in)activity period for a specific server.

**Comment by gitfirewall** [comment] 2026-03-31 08:56
I strongly request this feature!
