### ISSUE TITLE
The Standard DNS blocks online helper on https://meest-express.com.ua

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#168] opened 2017-07-31 13:57 UTC
They use https://static.siteheart.com provider.

### Steps to reproduce

1. Go https://meest-express.com.ua
2. Start a chat
3. ...
4. No reply, I assume they don't see your dialogue or something

### Expected behavior

You get an answer

### Actual behavior

It hangs like this:

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28780968-358df57c-7611-11e7-8bd2-f22f3e1f7a13.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default, 176.103.130.130 (131)
| How did you setup DNS configuration:| Router |
| Device model:| Windows PC
| Operating system and version:| Windows 10

**Comment by evgeniy-ADG** [comment] 2017-09-01 14:26
I can be wrong but it seems to me that other online helper providers have the same issue. Vodafone Ukraine uses https://messenger.providesupport.com/ and I could not reach them until I removed the DNS from my router.

**Comment by Alex-302** [comment] 2017-09-04 08:35
I can't reproduce this issue. 
@zebrum could you check?

**Comment by zebrum** [comment] 2017-09-04 09:10
It's ok with DNScrypt.
On my side It seems the issue is connected with ad blocking (Adguard for windows)

**Comment by nkartyshov** [comment] 2017-10-06 09:40
@Alex-302 @zebrum 
Is this issue resolved? Can I close it?

**Comment by Alex-302** [comment] 2017-10-06 10:29
I can't reproduce the issue.

<details>

![image](https://user-images.githubusercontent.com/8361299/31274132-4f12893c-aa9a-11e7-889e-2c6c957c855f.png)

</details>

**Comment by zebrum** [comment] 2017-10-11 09:50
@evgeniy-ADG is it still reproducible on your side,

**Closed** 2017-12-08 13:50 UTC
