### ISSUE TITLE
[Feature Request] AdGuard server location map

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#345] opened 2022-08-18 18:02 UTC
I'd love to see an AdGuard server map get added somewhere, like the AdGuard homepages for each product showing the location of each server on the map, the abbreviation used for that server, and the current ping.

**Comment by planet0** [comment] 2022-08-19 07:46
This might be a duplicate of https://github.com/AdguardTeam/AdGuardDNS/issues/210

**Closed as completed** 2022-08-19 07:48 UTC
