### ISSUE TITLE
High latency with Singapore ViewQwest ISP

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardDNS#449] opened 2022-11-14 06:28 UTC
> I'm a user from Singapore and I've been noticing my latency to be around 80-100ms while using Adguard DNS.
> I am being routed to the Tokyo servers supposedly, is there any way the team can help me with this?

Traceroute results in helpdesk: 676144

**Comment by ameshkov** [comment] 2022-11-14 19:35
We need traceroute at least

**Comment by Eugene-Savenko** [comment] 2022-11-15 10:55
@ameshkov I am not sure if it's okay to post it here publicly, but it's in the ticket (676144).

**Comment by ameshkov** [comment] 2022-11-15 12:25
AS number would be enough.

The problem is with AS18106.

**Comment by D13410N3** [comment] 2022-11-16 17:12
Issue should be fixed now

**Closed by D13410N3** 2022-11-16 17:12 UTC
Labels: routing
