### ISSUE TITLE
PayPal is not being resolved!

### ISSUE THREAD

**Issue by Nestorbra** [AdguardTeam/AdguardDNS#88] opened 2016-11-20 10:11 UTC
Dejar all,

AdguardDNS (default) is not resolving any PayPal site. Could you please check on your side?

Regards!

**Comment by Alex-302** [comment] 2016-11-20 11:10
please list here paypal domains, which are not resolving

**Comment by Nestorbra** [comment] 2016-11-20 11:43
Hi Alex,

It is not resolving the main domain (paypal.com). Country TLD just redirects to the main domain / country sub site. So if the main domain is not resolved we are not able to access no any PayPal site :-(

Regards!

**Comment by Alex-302** [comment] 2016-11-20 12:07
please enter these commands to cmd end make screenshots or copy as text
nslookup paypal.com 176.103.130.130
nslookup paypal.com 176.103.130.131
tracert paypal.com

**Comment by Nestorbra** [comment] 2016-11-20 13:43
Alex,

See the attached screenshots below:

![nslookup](https://cloud.githubusercontent.com/assets/23265100/20463225/8bbd5c52-af2f-11e6-93d7-6142040e8939.png)
![traceroute](https://cloud.githubusercontent.com/assets/23265100/20463224/8bbcb5ae-af2f-11e6-9d18-e962953b68a4.png)
![dnsleaktest](https://cloud.githubusercontent.com/assets/23265100/20463226/8bbe0dfa-af2f-11e6-9826-6d9ed0b7bd68.png)
![paypal_geotool](https://cloud.githubusercontent.com/assets/23265100/20463227/8bbf4b8e-af2f-11e6-8d50-8be5dcf4fe47.png)

**Comment by Alex-302** [comment] 2016-11-20 13:52
Are you in Western Europe?

**Comment by Nestorbra** [comment] 2016-11-20 13:54
Yes, I'm. 

Can you also reproduce the issue?

**Comment by Alex-302** [comment] 2016-11-20 13:59
Yes, reproduced.

**Comment by Alex-302** [comment] 2016-11-20 14:00
@nkartyshov could you please help?

**Comment by ameshkov** [comment] 2016-11-20 18:59
The issue is resolved now.

**Closed by ameshkov** 2016-11-20 18:59 UTC
Labels: bug
