### ISSUE TITLE
www.pornhub.com is not blocked by parental control (DNS)

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardDNS#327] opened 2018-09-07 11:03 UTC
www.pornhub.com is not blocked by parental control (DNS)

**Comment by hmage** [comment] 2018-09-07 11:08
NOTE: This affects adguard DNS servers -- underlying issue has already been fixed in this repository and servers will be updated within short timeframe.

**Comment by hmage** [comment] 2018-09-07 12:39
New servers rolled out, fixes this and similar issues of subdomains not matching while domains are.

**Closed by hmage** 2018-09-07 12:39 UTC

**Comment by almostserious** [comment] 2020-05-27 12:24
This seems to be the case again? While other sites get filtered by parental control, the pronhub.com is not filtered anymore.

**Comment by ameshkov** [comment] 2020-05-27 12:38
@almostserious cannot reproduce this

What sites are blocked?

**Comment by almostserious** [comment] 2020-05-27 14:26
Nevermind... the issue is of a different kind. 
I just realized that my network uses the 2nd DNS for a lot of blocked sites if my Ad Guard Home does not answer. Not sure yet if that is just always using the 2nd DNS because its faster, or only for the blocked pages... anyway I deleted the fallback 2nd DNS (intention was to use this in case AdGuard Home is down) and everything works as expected.

**Comment by Archive5** [comment] 2020-05-27 21:13
> Not sure yet if that is just always using the 2nd DNS because its faster

You can use it in AGH

>2nd DNS (intention was to use this in case AdGuard Home is down)

Run two AGH instances
