### ISSUE TITLE
Adguard DNS Default IPs Blocking Nvidia Geforce Experience From Downloading Drivers 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#31] opened 2016-08-18 06:14 UTC
I would like to report that the default IPs for Adguard DNS seem to be blocking the Nvidia Geforce Experience program from downloading my graphics card drivers, I had to disable Adguard DNS to start the download, and I tested this again by re-enabling Adguard DNS and the download would fail.

Today there was a Geforce Game Ready Driver 372.54 that the Nvidia Geforce Experience alerted me about, but it can not be downloaded through the program while Adguard DNS is enabled.
<details>
![aduard dns blocks nvidia driver download](https://cloud.githubusercontent.com/assets/15856304/17804255/5bb68e68-6603-11e6-992a-0c1a0723965f.png)
</details>
**1285994**

**Comment by Alex-302** [comment] 2016-08-19 07:17
Can't reproduce.

**Comment by Bohdan-SUP** [comment] 2016-08-31 10:51
User confirmed it's working fine now. Can we close it now?

**Comment by Alex-302** [comment] 2016-08-31 10:52
Yes

**Closed by Alex-302** 2016-08-31 10:52 UTC
Labels: question
