### ISSUE TITLE
'Reconnect device' scrolls to the bottom of next page

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#278] opened 2022-06-14 21:34 UTC
When tapping the 'Reconnect device' button, instead of going to the top of the next page, it seems to go to the bottom.

https://user-images.githubusercontent.com/95468948/173693044-2c4c75e0-5dd5-4370-b741-0bdc8bb62266.MOV

**Comment by Chinaski1** [comment] 2022-07-13 16:29
The issue is fixed in the latest update.

**Closed by Chinaski1** 2022-07-13 16:29 UTC
Labels: bug
