### ISSUE TITLE
Huawei

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardDNS#124] opened 2020-11-30 13:16 UTC
@mariusz689 commented on [Sun Nov 29 2020](https://github.com/AdguardTeam/AdguardFilters/issues/68862)

I have the default AdGuard DNS filters on Mikrotik.
AdGuard DNS IP: 94.140.14.14
The problem is that the connection for the Huawei Inverter is blocked and the connection for the Fusionsolar application is blocked.
The problem does not occur when logging in to the account via the browser: https://eu5.fusionsolar.huawei.com/

I tried to solve the problem in this thread (but still the problem is not resolved): https://github.com/MajkiIT/polish-ads-filter/issues/17875

You can test it for yourself by downloading the FusionSolar application from the google store. In the application, enter a random username and password. A message about a problem with internet connection will be displayed if the AdGuard DNS filter is active. Otherwise, when the application works properly, a message with an incorrect username or password will be returned.

Could you please investigate the problem?

---

@zaba-monika commented on [Sun Nov 29 2020](https://github.com/AdguardTeam/AdguardFilters/issues/68862#issuecomment-735413959)

Poprawka z mojej strony, do problemów z DNS AdGuard jest osobny tracker:
(my apologies, I've provided him wrong link, the proper tracker for AdGuard DNS issues is):
 https://github.com/AdguardTeam/AdGuardSDNSFilter/issues

---

@krystian3w commented on [Sun Nov 29 2020](https://github.com/AdguardTeam/AdguardFilters/issues/68862#issuecomment-735441666)

This is performacne issue with AdGuard DNS; generate lag - ping 20-60k ms (20-60 seconds) for comeback request from `103.235.46.39:443` (Baidu / `shifen.com`)

**Comment by ameshkov** [comment] 2020-11-30 13:50
`shifen.com` is resolved quickly, I don't get it

**Comment by mariusz689** [comment] 2020-12-01 00:38
The inverter is probably connecting to the server 104.193.88.123:443 or 103.235.46.39:443 for account authorization
and here's the problem. When AdGuard DNS is active: 94.140.14.14 or 94.140.14.15 or 94.140.14.140 in the fusionsolar phone application, the "Internet connection problem" message is returned when logging in. When I disable AdGuard DNS, the fusionsolar application starts up properly.

**Comment by ameshkov** [comment] 2020-12-02 10:34
What's important for me to understand is which domain is not resolved or resolved with problems.

@mariusz689 could you please try installing [AdGuard for Android](https://adguard.com/adguard-android/overview.html), configuring DNS there and inspecting the filtering log when the issue is reproduced.

DNS filtering functionality is free in AG for Android so this shouldn't be a problem.

**Comment by krystian3w** [comment] 2020-12-02 10:39
Should be see lag/ping 20000-60000 ms for request `103.235.46.39:443` marked as `www.baidu.com` / CNAME `a.shifen.com`.

**Comment by ameshkov** [comment] 2020-12-02 10:41
Seems to be okay on my side:

```
% time dnslookup www.baidu.com quic://dns.adguard.com
dnslookup v1.4.4
dnslookup result:
;; opcode: QUERY, status: NOERROR, id: 14661
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.baidu.com.	IN	 A

;; ANSWER SECTION:
www.baidu.com.	157	IN	CNAME	www.a.shifen.com.
www.a.shifen.com.	157	IN	CNAME	www.wshifen.com.
www.wshifen.com.	157	IN	A	104.193.88.123
www.wshifen.com.	157	IN	A	104.193.88.77

dnslookup www.baidu.com quic://dns.adguard.com  0.06s user 0.02s system 16% cpu 0.507 total
```

```
% time dnslookup a.shifen.com quic://dns.adguard.com
dnslookup v1.4.4
dnslookup result:
;; opcode: QUERY, status: NOERROR, id: 47806
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;a.shifen.com.	IN	 A

;; AUTHORITY SECTION:
a.shifen.com.	418	IN	SOA	ns1.a.shifen.com. baidu_dns_master.baidu.com. 2012020011 5 5 2592000 3600

dnslookup a.shifen.com quic://dns.adguard.com  0.06s user 0.03s system 11% cpu 0.831 total
```

**Comment by zaba-monika** [comment] 2020-12-02 12:42
> ameshkov : https://github.com/AdguardTeam/AdGuardDNS/issues/124#issuecomment-737143138 : What's important for me to understand is which domain is not resolved or resolved with problems.
>
> @mariusz689 could you please try installing [AdGuard for Android](https://adguard.com/adguard-android/overview.html), configuring DNS there and inspecting the filtering log when the issue is reproduced.

- we still don't know for sure...we actually have been hope it will be `AdGuard` who will answer that question...
by installing `Fusionsolar` on `Android` and debug the issue...
- but instead we hear now we are the ones who should install `AdGuard` on `Android` and debug the issue...


> ameshkov : #124 (comment) : DNS filtering functionality is free in AG for Android so this shouldn't be a problem.

- he has already been trying be he crashed https://github.com/MajkiIT/polish-ads-filter/issues/17875#issuecomment-735447959 :smiley:

**Comment by ameshkov** [comment] 2020-12-02 14:39
> we still don't know for sure...we actually have been hope it will be AdGuard who will answer that question...
> by installing Fusionsolar on Android and debugging the issue...

Well, the issue is not reproduced on our side.

When trying to reproduce this issue, we see a different error: the user does not exist or password is wrong.

> he has already been trying but he crashed importing the DNS filter MajkiIT/polish-ads-filter#17875 (comment) 😃 , so there is a problem for him...

Oh, he definitely used a wrong URL for the DNS filter.

Anyways, there's no need to import any filter, it's enough just to enable AdGuard DNS.

**Comment by mariusz689** [comment] 2020-12-02 23:06
[FusionSolar Problem.zip](https://github.com/AdguardTeam/AdGuardDNS/files/5632525/FusionSolar.Problem.zip)

Earlier, I downloaded the AdGuard application from the google store and it was a limited version that practically does not work.

Now I downloaded the application from the official AdGuard website and activated the test full version.

I put screenshots in the .zip file.
The first two photos are when the FusionSolar application starts correctly (With active filters only on the phone). In the third photo I showed that I turned on AdGuard DNS. The FusionSolar application has stopped working. I get the message "no internet connection, ...". In next the following photos, the application no longer works.

**Comment by ameshkov** [comment] 2020-12-03 08:45
Hm, I see nothing wrong with the DNS resolution here and it bothers me that I cannot reproduce this issue myself:(

Are you sure the issue is caused by the wrong resolution of `www.baidu.com` and not some other domain?

Let's test it and force `www.baidu.com` to use the IP address you were mentioning.

In order to do this:

1. Go to settings -> DNS -> DNS requests blocking -> DNS user filter
2. Add `104.193.88.123     www.baidu.com` there

This will make AdGuard return the specified IP address instead.

**Comment by mariusz689** [comment] 2020-12-03 17:46
Maybe you don't have problems with this application because you live in a different part of the world than Poland. Where I live, I connect to servers other than you? Maybe make yourself a VPN connection with some server in Poland? and then you test the Fusionsolar app?

I have observed a certain situation. There are situations that I can log in to FusionSolar 4 times in a row. There were problems from the fifth attempt "problem with internet connection". Later, when I try to log in several times in a row, the message "problem with internet connection?". After some time, probably about 8 hours, I can log in again several times in a row and again there is a message about "problem with internet connection"

In the AdGuard application I did as you said, okay?
Attached are screenshots
[FusionSolar problem v2.zip](https://github.com/AdguardTeam/AdGuardDNS/files/5637939/FusionSolar.problem.v2.zip)

**Comment by krystian3w** [comment] 2020-12-03 18:33
I suppose still live in Russia 🇷🇺.

**Comment by ameshkov** [comment] 2020-12-04 11:39
> In the AdGuard application I did as you said, okay?

Did it help?

**Comment by mariusz689** [comment] 2020-12-04 11:59
Did not help. it's still the same. Today, when I try to log in to FusionSolar for the first time, I still get the message "Network is malfunctioning. Please connect phone to internet"

**Comment by ameshkov** [comment] 2020-12-04 12:20
Well, it just means the problem is not with `www.baidu.com`.

Tbh, I've no clue how to solve this as I still don't understand what's causing it.
In the case of the AdGuard app, the temporary solution would be disabling filtering for that app: settings -> apps management -> find the app -> go to app details -> uncheck "enabled"

**Comment by krystian3w** [comment] 2020-12-04 12:34
But he use AdGuard DNS on MikroTik router, app on telephone only help to better debug than MikroTik has.

**Comment by ameshkov** [comment] 2020-12-04 13:14
Well, that's a problem indeed.

Since the issue cannot be reproduced on our side, the only thing left is experimenting with the app and trying to figure out which domain is responsible for that.

Record domains/IP addresses that the app uses
Use your ISP's DNS to resolve them
Add these pairs (domain + IP from ISP) to the DNS user filter in AdGuard
Once it starts working stably, you can start removing domains from the DNS user filter one by one

This way we can understand what domain causes issues.

**Comment by mariusz689** [comment] 2020-12-14 14:24
I haven't noticed any problems running the FusionSolar app on my phone for several days. I haven't changed the settings, I'm still using AdGuard DNS. Did the problem fix itself? have you changed anything on your servers regarding my problem?

I remind you that a few weeks ago when I was using AdGuard DNS on Mikrotik and even selecting DNS "No filtering" the problem was occurring.

Is the AdGuard DNS filter "no filtering" devoid of any blocking rules? What is this filter for?

**Comment by ameshkov** [comment] 2020-12-14 16:54
> Did the problem fix itself? have you changed anything on your servers regarding my problem?

Seems so, we haven't changed anything:)

> Is the AdGuard DNS filter "no filtering" devoid of any blocking rules? What is this filter for?

If you just need a DNS service without logging.

**Closed by ameshkov** 2020-12-14 16:54 UTC
