### ISSUE TITLE
AdGuard DNS sporadically blocks PayPal interstitial links

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardDNS#14] opened 2019-02-15 13:14 UTC
AdGuard DNS (176.103.130.130, 176.103.130.131) sporadically blocks PayPal interstitial links like https://epl.paypal-communication.com/T/v400000168eb124736a9bc7af4bbe5c898/b5afd432b91449400000021ef3a0bcc6/b5afd432-b914-4940-9b78-6d409cf02610?__dU__=v0G4RBKTXg2GtDSXU69hUjn5RqR7EEyYkx
,

as reported by user 2116559

**Comment by hmage** [comment] 2019-02-15 13:17
The hostname is in the filters:

```
$ curl -s https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt | fgrep paypal
||stats.paypal.com^
||t.paypal.com^
||epl.paypal-communication.com^
```

**Comment by ameshkov** [comment] 2019-02-15 13:37
@Alex-302 could you please assist?

**Comment by Alex-302** [comment] 2019-02-15 17:52
Caused by EasyPrivacy rule.
Fixed by https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/46

**Closed** 2019-04-18 18:09 UTC
