### ISSUE TITLE
Filtering rules showing wrong status for domains being blocked or unblocked

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#482] opened 2022-12-21 16:13 UTC
Adgaurd DNS is showing the domain www.google.com as Top blocked even though its unblocked from a blacklists that I enabled. There might be other domains but I just noticed this with the google domain. 

![Screenshot_20221219_190811_Samsung Internet](https://user-images.githubusercontent.com/96619913/208950759-db2dd0af-d39e-4adf-983f-73d8f7900130.jpg)
![Screenshot_20221219_190832_Samsung Internet](https://user-images.githubusercontent.com/96619913/208950764-6805a7c2-32f4-4702-bba0-fac6f7a02094.jpg)

**Comment by Chinaski1** [comment] 2022-12-21 16:47
Most likely the number of blocked requests was collected in the statistics before the domain was allowlisted, so it shows as top blocked

**Comment by Batman2814** [comment] 2022-12-21 16:49
It's not a bug and should disappear

**Comment by ameshkov** [comment] 2022-12-21 18:45
Why, statistics reflects what happened in a period of time. And it correctly shows that `www.google.com` was the top blocked domain.

**Comment by Batman2814** [comment] 2022-12-29 13:18
![Screenshot_20221229_071419_Samsung Internet](https://user-images.githubusercontent.com/96619913/209956853-0d58166e-be95-4b44-8a72-ae03957ae86f.jpg)

This was taking on Samsung Galaxy tablet were its showing the domain www.google.com as top requested and not top locked my my Samsung phone is showing www.google.com as top blocked.

**Comment by Batman2814** [comment] 2022-12-29 13:21
![Screenshot_20221229_071942_Samsung Internet](https://user-images.githubusercontent.com/96619913/209958279-372f0a0b-9ada-471b-a319-6f34c39cca2e.jpg)

On my Samsung phone

**Comment by Batman2814** [comment] 2023-01-11 21:47
Can anyone from Adguard explain this?

**Comment by Chinaski1** [comment] 2023-01-13 12:35
Could you provide screenshots from the companies page where the issue is displayed?

**Comment by Batman2814** [comment] 2023-01-13 13:46
I did provide screen shots and what company are you talking about. This issue is with adgaurd DNS. It's show different results on a different device. The only thing is allow other devices show www.google.com is the top requested and it's only on my phone that it showing it is Top blocked. This is in real time.

**Comment by Chinaski1** [comment] 2023-01-18 16:39
@Batman2814 
Indeed the information about top blocked and top requested domains is different in the mobile and desktop version

**Comment by Chinaski1** [comment] 2023-02-03 09:18
Fixed in [v2.1.5](https://adguard-dns.io/en/versions.html#2.1.5)

**Closed by Chinaski1** 2023-02-03 09:18 UTC
Labels: bug
