### ISSUE TITLE
iPhones' App Store show some missing images with AdGuard DNS (DNS-over-HTTPS)'s filterings enabled. 

### ISSUE THREAD

**Issue by antdude** [AdguardTeam/AdGuardDNS#736] opened 2024-02-02 22:58 UTC
### Platform

iOS

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Your configuration

If I disable DNS protection or use AdGuard DNS Non-filtering, then the images show up. This was in AdGuard Pro v4.5.2(1010) both my iPhone 12 mini's iOS v17.3 and iPhone 6+'s iOS v12.5.7. Is anyone else seeing this too?

Thank you for reading and hopefully answering soon. :)

### Issue Details

1. Be sure AdGuard Pro's iOS app is updated and using AdGuard DNS (DNS-over-HTTPS) filterings in iPhone.

2. Go to iOS' App Store and look at apps.

### Expected Behavior

All images show up.

### Actual Behavior

Some images are missing.

### Screenshots

https://imgchest.com/p/na7kzb5j378 for a couple screen shots from my iPhone 12 mini.

**Comment by donald2612** [comment] 2024-02-03 14:02
Yes, exactly yesterday evening, I was pulling my hair because I was fine-tuning some rules for Apple-domains on my AdguardHome-installations. Their are pulling from upstream QUIC AdguardDNS-Servers. I gave up @ 2o'clock in the morning and went to bed. This morning it was fixed. The icons all re-appeared again. Clearly had to do with apple-domains....
I was relieved when I saw this here!

**Comment by antdude** [comment] 2024-02-03 15:10
I still see this problem. :(

**Comment by antdude** [comment] 2024-02-03 15:13
OK. Killing and relaunching App Store app fixed it. Not sure why it didn't work before doing that.

**Comment by donald2612** [comment] 2024-02-03 15:17
May have not been a problem with Adguard itself, but its curated blocklists. I am using these:

![grafik](https://github.com/AdguardTeam/AdGuardDNS/assets/57543527/3e107f6b-366f-4b23-a057-aa5c28aa04e5)

**Comment by Chinaski1** [comment] 2024-02-05 15:05
Since the problem was caused by one of the rules in third-party filters, I am closing this task as solved

**Closed as completed by Chinaski1** 2024-02-05 15:05 UTC
Labels: bug
